//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.Steam.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.Steam.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;appID&gt;247080&lt;/appID&gt;
        ///  &lt;appFriendlyName&gt;247080&lt;/appFriendlyName&gt;
        ///  &lt;leaderboardID&gt;2047387&lt;/leaderboardID&gt;
        ///  &lt;totalLeaderboardEntries&gt;317&lt;/totalLeaderboardEntries&gt;
        ///  &lt;entryStart&gt;0&lt;/entryStart&gt;
        ///  &lt;entryEnd&gt;317&lt;/entryEnd&gt;
        ///  &lt;resultCount&gt;317&lt;/resultCount&gt;
        ///  &lt;entries&gt;
        ///    &lt;entry&gt;
        ///      &lt;steamid&gt;76561197998799529&lt;/steamid&gt;
        ///      &lt;score&gt;134377&lt;/score&gt;
        ///      &lt;rank&gt;1&lt;/rank&gt;
        ///      &lt;ugcid&gt;849347241492683863&lt;/ugcid&gt;
        ///      &lt;details&gt;&lt;![C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeaderboardEntries {
            get {
                return ResourceManager.GetString("LeaderboardEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;appID&gt;247080&lt;/appID&gt;
        ///  &lt;appFriendlyName&gt;247080&lt;/appFriendlyName&gt;
        ///  &lt;leaderboardCount&gt;411&lt;/leaderboardCount&gt;
        ///  &lt;leaderboard&gt;
        ///    &lt;url&gt;http://steamcommunity.com/stats/247080/leaderboards/2047387/?xml=1&lt;/url&gt;
        ///    &lt;lbid&gt;2047387&lt;/lbid&gt;
        ///    &lt;name&gt;DLC HARDCORE All Chars DLC_PROD&lt;/name&gt;
        ///    &lt;display_name&gt;All Characters (DLC) Score (Amplified)&lt;/display_name&gt;
        ///    &lt;entries&gt;317&lt;/entries&gt;
        ///    &lt;sortmethod&gt;2&lt;/sortmethod&gt;
        ///    &lt;displaytype&gt;1&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leaderboards {
            get {
                return ResourceManager.GetString("Leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;players&quot;: [
        ///    {
        ///      &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///      &quot;communityvisibilitystate&quot;: 3,
        ///      &quot;profilestate&quot;: 1,
        ///      &quot;personaname&quot;: &quot;Robin&quot;,
        ///      &quot;lastlogoff&quot;: 1501731437,
        ///      &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///      &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///      &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaries {
            get {
                return ResourceManager.GetString("PlayerSummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;response&quot;: {
        ///    &quot;players&quot;: [
        ///      {
        ///        &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///        &quot;communityvisibilitystate&quot;: 3,
        ///        &quot;profilestate&quot;: 1,
        ///        &quot;personaname&quot;: &quot;Robin&quot;,
        ///        &quot;lastlogoff&quot;: 1501731437,
        ///        &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///        &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///        &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/im [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummariesEnvelope {
            get {
                return ResourceManager.GetString("PlayerSummariesEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///}.
        /// </summary>
        internal static string PlayerSummariesEnvelopeWithoutResponse {
            get {
                return ResourceManager.GetString("PlayerSummariesEnvelopeWithoutResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;response&quot;: {
        ///    &quot;players&quot;: [
        ///      {
        ///        &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///        &quot;communityvisibilitystate&quot;: 3,
        ///        &quot;personaname&quot;: &quot;Robin&quot;,
        ///        &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///        &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///        &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummariesWithoutLastLogOff {
            get {
                return ResourceManager.GetString("PlayerSummariesWithoutLastLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///}.
        /// </summary>
        internal static string PlayerSummariesWithoutPlayers {
            get {
                return ResourceManager.GetString("PlayerSummariesWithoutPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;profilestate&quot;: 1,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummary {
            get {
                return ResourceManager.GetString("PlayerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_full.jpg&quot;,
        ///  &quot;personastate&quot;: 0
        ///}.
        /// </summary>
        internal static string PlayerSummaryWithoutAvatar {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;personastate&quot;: 0
        ///}.
        /// </summary>
        internal static string PlayerSummaryWithoutAvatarFull {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutAvatarFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_full.jpg&quot;,
        ///  &quot;personastate&quot;: 0
        ///}.
        /// </summary>
        internal static string PlayerSummaryWithoutAvatarMedium {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutAvatarMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaryWithoutCommunityVisibilityState {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutCommunityVisibilityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaryWithoutLastLogOff {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutLastLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaryWithoutPersonaName {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutPersonaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaih [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaryWithoutPersonaState {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutPersonaState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;steamid&quot;: &quot;76561197960435530&quot;,
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaryWithoutProfileUrl {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;communityvisibilitystate&quot;: 3,
        ///  &quot;personaname&quot;: &quot;Robin&quot;,
        ///  &quot;lastlogoff&quot;: 1501731437,
        ///  &quot;profileurl&quot;: &quot;http://steamcommunity.com/id/robinwalker/&quot;,
        ///  &quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4.jpg&quot;,
        ///  &quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/f1/f1dd60a188883caf82d0cbfccfe6aba0af1732d4_medium.jpg&quot;,
        ///  &quot;avatarfull&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSummaryWithoutSteamId {
            get {
                return ResourceManager.GetString("PlayerSummaryWithoutSteamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;response&quot;: {
        ///		&quot;players&quot;: [
        ///			{
        ///				&quot;steamid&quot;: &quot;76561198000971575&quot;,
        ///				&quot;communityvisibilitystate&quot;: 3,
        ///				&quot;profilestate&quot;: 1,
        ///				&quot;personaname&quot;: &quot;TheFaceless&quot;,
        ///				&quot;lastlogoff&quot;: 1505533192,
        ///				&quot;commentpermission&quot;: 1,
        ///				&quot;profileurl&quot;: &quot;http://steamcommunity.com/profiles/76561198000971575/&quot;,
        ///				&quot;avatar&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/ee/ee5a1c8fdc1939ff4d83ed2d36ad279766a367a5.jpg&quot;,
        ///				&quot;avatarmedium&quot;: &quot;https://steamcdn-a.akamaihd.net/steamcommunity/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StarWarsEncoding {
            get {
                return ResourceManager.GetString("StarWarsEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWN DIREBAT%*#%*24\n1\n0\n0\n1\n1\n0\n1\n107608\n2\n1006686362\n1\n512\n337\n170\n0|170|2:2,4:2,6:2,8:2,10:2,12:3,14:3,16:3,18:3,20:3,22:3,24:3,26:2,28:3,30:0,32:3,34:2,36:3,38:3,40:2,42:0,44:2,46:0,48:0,50:0,52:0,54:3,56:3,58:2,60:3,62:2,64:1,66:3,68:3,70:3,72:2,74:2,76:2,78:2,80:0,82:3,84:3,86:0,88:0,90:3,92:3,94:1,96:1,98:1,100:1,102:1,104:1,106:1,108:1,110:1,112:1,114:1,116:1,118:1,120:1,122:2,124:1,126:1,128:2,130:0,132:2,134:0,136:2,138:2,140:2,142:2,144:2,146:2,148:2,150:1,152:2,154:1,156:1,158:1,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UgcFile {
            get {
                return ResourceManager.GetString("UgcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;filename&quot;: &quot;2/9/2014_score191_zone1_level2&quot;,
        ///  &quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/22837952671856412/756063F4E07B686916257652BBEB972C3C9E6F8D/&quot;,
        ///  &quot;size&quot;: 1558
        ///}.
        /// </summary>
        internal static string UgcFileDetails {
            get {
                return ResourceManager.GetString("UgcFileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;filename&quot;: &quot;2/9/2014_score191_zone1_level2&quot;,
        ///    &quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/22837952671856412/756063F4E07B686916257652BBEB972C3C9E6F8D/&quot;,
        ///    &quot;size&quot;: 1558
        ///  }
        ///}.
        /// </summary>
        internal static string UgcFileDetailsEnvelope {
            get {
                return ResourceManager.GetString("UgcFileDetailsEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///}.
        /// </summary>
        internal static string UgcFileDetailsEnvelopeWithoutData {
            get {
                return ResourceManager.GetString("UgcFileDetailsEnvelopeWithoutData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/22837952671856412/756063F4E07B686916257652BBEB972C3C9E6F8D/&quot;,
        ///  &quot;size&quot;: 1558
        ///}.
        /// </summary>
        internal static string UgcFileDetailsWithoutFileName {
            get {
                return ResourceManager.GetString("UgcFileDetailsWithoutFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;filename&quot;: &quot;2/9/2014_score191_zone1_level2&quot;,
        ///  &quot;url&quot;: &quot;http://cloud-3.steamusercontent.com/ugc/22837952671856412/756063F4E07B686916257652BBEB972C3C9E6F8D/&quot;
        ///}.
        /// </summary>
        internal static string UgcFileDetailsWithoutSize {
            get {
                return ResourceManager.GetString("UgcFileDetailsWithoutSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;filename&quot;: &quot;2/9/2014_score191_zone1_level2&quot;,
        ///  &quot;size&quot;: 1558
        ///}.
        /// </summary>
        internal static string UgcFileDetailsWithoutUrl {
            get {
                return ResourceManager.GetString("UgcFileDetailsWithoutUrl", resourceCulture);
            }
        }
    }
}
